apiVersion: apps/v1
kind: Deployment
metadata:
  name: aufgabe1-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aufgabe1-grpc
  template:
    metadata:
      labels:
        app: aufgabe1-grpc
    spec:
      containers:
        - name: grpc-server
          image: aufgabe1-backend:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
